// contributorsData.js

module.exports = [
  { name: "Jesse", bio: "Daredevil, Photographer, Programmer" },
  { name: "JPack", bio: "Daredevil, Photographer, Programmer" },
  { name: "JMoney", bio: "Daredevil, Photographer, Programmer" },
  { name: "JP", bio: "Daredevil, Photographer, Programmer" },
  { name: "Jay", bio: "Daredevil, Photographer, Programmer" },
  { name: "David", bio: "Daredevil, Photographer, Programmer" },
  { name: "Jason", bio: "Daredevil, Photographer, Programmer" },
  { name: "Mike", bio: "Daredevil, Photographer, Programmer" },
  { name: "Pat", bio: "Daredevil, Photographer, Programmer" },
  { name: "Thomas", bio: "Daredevil, Photographer, Programmer" },
  { name: "Julie", bio: "Daredevil, Photographer, Programmer" },
  { name: "Katie", bio: "Daredevil, Photographer, Programmer" },
  { name: "Sam", bio: "Daredevil, Photographer, Programmer" },
  { name: "Hugh", bio: "Daredevil, Photographer, Programmer" },
  { name: "Sarah", bio: "Daredevil, Photographer, Programmer" },
  { name: "Kim", bio: "Daredevil, Photographer, Programmer" },
  { name: "Rob", bio: "Daredevil, Photographer, Programmer" },
  { name: "Maria", bio: "Daredevil, Photographer, Programmer" },
  { name: "Luke", bio: "Daredevil, Photographer, Programmer" },
  { name: "Amy", bio: "Daredevil, Photographer, Programmer" },
  { name: "Francy", bio: "Daredevil, Photographer, Programmer" },
  { name: "Lucas", bio: "Daredevil, Photographer, Programmer" },
  { name: "Robbie", bio: "Daredevil, Photographer, Programmer" },
  { name: "Louisa", bio: "Daredevil, Photographer, Programmer" },
  { name: "Christie", bio: "Daredevil, Photographer, Programmer" },
  { name: "Jhun", bio: "Daredevil, Photographer, Programmer" },
  { name: "DJR", bio: "Daredevil, Photographer, Programmer" },
  { name: "Hector", bio: "Daredevil, Photographer, Programmer" },
  { name: "Lola", bio: "Daredevil, Photographer, Programmer" },
  { name: "John", bio: "Daredevil, Photographer, Programmer" }
];