// contributorsData.js

module.exports = [
  { name: "Jesse", bio: "Daredevil, Photographer, Programmer", email: 'test@email.com', password: 'password'},
  { name: "JPack", bio: "Daredevil, Photographer, Programmer", email: 'test1@gmail.com', password: 'password'},
  { name: "JMoney", bio: "Daredevil, Photographer, Programmer", email: 'test2@gmail.com', password: 'password'},
  { name: "JP", bio: "Daredevil, Photographer, Programmer", email: 'test3@gmail.com', password: 'password'},
  { name: "Jay", bio: "Daredevil, Photographer, Programmer", email: 'test4@gmail.com', password: 'password'},
  { name: "David", bio: "Daredevil, Photographer, Programmer", email: 'test5@gmail.com', password: 'password'},
  { name: "Jason", bio: "Daredevil, Photographer, Programmer", email: 'test6@gmail.com', password: 'password'},
  { name: "Mike", bio: "Daredevil, Photographer, Programmer", email: 'test7@gmail.com', password: 'password'},
  { name: "Pat", bio: "Daredevil, Photographer, Programmer", email: 'test8@gmail.com', password: 'password'},
  { name: "Thomas", bio: "Daredevil, Photographer, Programmer", email: 'test9@gmail.com', password: 'password'},
  { name: "Julie", bio: "Daredevil, Photographer, Programmer", email: 'test10@gmail.com', password: 'password'},
  { name: "Katie", bio: "Daredevil, Photographer, Programmer", email: 'test11@gmail.com', password: 'password'},
  { name: "Sam", bio: "Daredevil, Photographer, Programmer", email: 'test12@gmail.com', password: 'password'},
  { name: "Hugh", bio: "Daredevil, Photographer, Programmer", email: 'test13@gmail.com', password: 'password'},
  { name: "Sarah", bio: "Daredevil, Photographer, Programmer", email: 'test14@gmail.com', password: 'password'},
  { name: "Kim", bio: "Daredevil, Photographer, Programmer", email: 'test15@gmail.com', password: 'password'},
  { name: "Rob", bio: "Daredevil, Photographer, Programmer", email: 'test16@gmail.com', password: 'password'},
  { name: "Maria", bio: "Daredevil, Photographer, Programmer", email: 'test17@gmail.com', password: 'password'},
  { name: "Luke", bio: "Daredevil, Photographer, Programmer", email: 'test18@gmail.com', password: 'password'},
  { name: "Amy", bio: "Daredevil, Photographer, Programmer", email: 'test19@gmail.com', password: 'password'},
  { name: "Francy", bio: "Daredevil, Photographer, Programmer", email: 'test20@gmail.com', password: 'password'},
  { name: "Lucas", bio: "Daredevil, Photographer, Programmer", email: 'test21@gmail.com', password: 'password'},
  { name: "Robbie", bio: "Daredevil, Photographer, Programmer", email: 'test22@gmail.com', password: 'password'},
  { name: "Louisa", bio: "Daredevil, Photographer, Programmer", email: 'test23@gmail.com', password: 'password'},
  { name: "Christie", bio: "Daredevil, Photographer, Programmer", email: 'test24@gmail.com', password: 'password'},
  { name: "Jhun", bio: "Daredevil, Photographer, Programmer", email: 'test25@gmail.com', password: 'password'},
  { name: "DJR", bio: "Daredevil, Photographer, Programmer", email: 'test26@gmail.com', password: 'password'},
  { name: "Hector", bio: "Daredevil, Photographer, Programmer", email: 'test27@gmail.com', password: 'password'},
  { name: "Lola", bio: "Daredevil, Photographer, Programmer", email: 'test28@gmail.com', password: 'password'},
  { name: "John", bio: "Daredevil, Photographer, Programmer", email: 'test29@gmail.com', password: 'password'}
];